label: 'LibriSpeech Multi-Task'
description: "Multi-Task training of AST, MT and ASR models on LibriSpeech"

data_dir: data/LibriSpeech
model_dir: models/LibriSpeech/AST_multitask
max_train_size: 10000

batch_size: 32
weight_scale: null

steps_per_checkpoint: 500
steps_per_eval: 500
max_steps: 500000

cell_size: 512
attn_size: 512
cell_type: LSTM

conv_filters: [16, 16]
conv_size: [3, 3]
conv_strides: [2, 2]
conv_activation: null
final_state: average
train_initial_states: False
bidir_projection: False
input_layers: [256, 128]

conditional_rnn: True
pred_deep_layer: True
use_previous_word: True
embedding_size: 128

tasks:
  - name: AST
    score_function: corpus_scores_bleu
    train_prefix: train+google
    ratio: 0.6

    encoders:
      - name: speech.en
        ext: npz
        embedding_size: 41
        layers: 3
        cell_size: 256
        binary: True
        max_len: 1400
    decoders:
      - name: char.fr
        character_level: True
        max_len: 300

  - name: ASR
    score_function: corpus_scores_wer
    train_prefix: train
    ratio: 0.2

    encoders:
      - name: speech.en
        ext: npz
        embedding_size: 41
        layers: 3
        cell_size: 256
        attn_size: 256
        binary: True
        bidir_projection: True
        max_len: 1400
    decoders:
      - name: char.en
        cell_size: 256
        character_level: True
        max_len: 300

  - name: MT
    score_function: corpus_scores_bleu
    train_prefix: train+google
    ratio: 0.2

    encoders:
      - name: sub.en
        embedding_size: 256
        bidir_projection: True
        train_initial_states: True
        input_layers: null
        conv_filters: null
        max_len: 60
    decoders:
      - name: char.fr
        character_level: True
        max_len: 300


use_dropout: True
pervasive_dropout: True
attn_dropout: 0.2
rnn_input_dropout: 0.2
initial_state_dropout: 0.2
input_layer_dropout: 0.2
