label: "ENCDEC-MCGRU MEDIUM"
description: "AMU 2017 Multi-Encoder Cond-GRU Model - 23k train set"

cell_size: 256
attn_size: 512
embedding_size: 128
cell_type: GRU

data_dir: data/AMU
max_len: 50
model_dir: models/AMU/medium

steps_per_checkpoint: 1000
steps_per_eval: 1000
keep_best: 4
score_function: corpus_scores_ter

batch_size: 32
max_gradient_norm: 1.0
max_steps: 150000

attention_type: global
final_state: average

weight_scale: 0.01

use_dropout: True
pervasive_dropout: True
rnn_input_dropout: 0.4
rnn_output_dropout: 0.4
word_dropout: 0.2

train_initial_states: False

encoders:
  - name: de
    ext: mt
  - name: src

decoders:
  - name: de
    ext: pe
    conditional_rnn: True
    pred_deep_layer: False
    pred_embed_proj: True
    tie_embeddings: True

ref_ext: pe.ref

post_process_script: config/AMU/post-process.sh
